// <auto-generated />
using System;
using Dotnet.Saga.Stock.API.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet.Saga.Stock.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dotnet.Saga.Stock.API.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("tb_product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b584159e-eeac-4586-bd76-557249d61daf"),
                            CreatedAt = new DateTime(2024, 2, 27, 12, 29, 32, 5, DateTimeKind.Utc).AddTicks(9295),
                            CurrentValue = 4459m,
                            IsDeleted = false,
                            Name = "PS5"
                        },
                        new
                        {
                            Id = new Guid("20db60a4-c53d-4afd-a1ad-42d15f470e2c"),
                            CreatedAt = new DateTime(2024, 2, 27, 12, 29, 32, 5, DateTimeKind.Utc).AddTicks(9327),
                            CurrentValue = 3999m,
                            IsDeleted = false,
                            Name = "XBOX Series X"
                        },
                        new
                        {
                            Id = new Guid("5f36da7e-7c77-4ea5-b65f-1bf3744fdc78"),
                            CreatedAt = new DateTime(2024, 2, 27, 12, 29, 32, 5, DateTimeKind.Utc).AddTicks(9331),
                            CurrentValue = 2199m,
                            IsDeleted = false,
                            Name = "XBOX Series S"
                        });
                });

            modelBuilder.Entity("Dotnet.Saga.Stock.API.Entities.StockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("tb_stock", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e45f9f6-738b-433c-a9b2-2350b38b5322"),
                            Amount = 30,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 29, 32, 5, DateTimeKind.Utc).AddTicks(9445),
                            IsDeleted = false,
                            ProductId = new Guid("b584159e-eeac-4586-bd76-557249d61daf")
                        },
                        new
                        {
                            Id = new Guid("33c33659-0b4b-4667-9051-62382c64ceab"),
                            Amount = 30,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 29, 32, 5, DateTimeKind.Utc).AddTicks(9450),
                            IsDeleted = false,
                            ProductId = new Guid("20db60a4-c53d-4afd-a1ad-42d15f470e2c")
                        },
                        new
                        {
                            Id = new Guid("4fa4615d-40d1-42f7-b539-4d2f74adfa0d"),
                            Amount = 30,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 29, 32, 5, DateTimeKind.Utc).AddTicks(9452),
                            IsDeleted = false,
                            ProductId = new Guid("5f36da7e-7c77-4ea5-b65f-1bf3744fdc78")
                        });
                });

            modelBuilder.Entity("Dotnet.Saga.Stock.API.Entities.StockHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("tb_stock_history", (string)null);
                });

            modelBuilder.Entity("Dotnet.Saga.Stock.API.Entities.StockEntity", b =>
                {
                    b.HasOne("Dotnet.Saga.Stock.API.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dotnet.Saga.Stock.API.Entities.StockHistoryEntity", b =>
                {
                    b.HasOne("Dotnet.Saga.Stock.API.Entities.StockEntity", "Stock")
                        .WithMany("StockHistory")
                        .HasForeignKey("StockId");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Dotnet.Saga.Stock.API.Entities.StockEntity", b =>
                {
                    b.Navigation("StockHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
